version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///%kernel.project_dir%/var/data.db}
    volumes:
      - './app/:/usr/src/app'
      - '/usr/src/app/var'
      - '/usr/src/app/vendor'
  nginx:
    image: nginx:1.17.6-alpine
    restart: on-failure
    volumes:
      - './app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT:-8082}:80'
    depends_on:
      - php